### PR TITLE
Draft of non-promotable clone docs

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Docs for https://github.com/EventStore/EventStore/pull/1751

@riccardone can you let me know if this is all accurate?

### CODE REVIEW

**Comment by riccardone** [comment]
I agree @gregoryyoung and other than add a new Role in this page we also need a full page about what it actually does

**Comment by ChrisChinchilla** [comment]
@riccardone and @gregoryyoung try these changes. Not quite sure why NPC needs a whole page though, unless I'm missing something?

**Comment by ChrisChinchilla** [comment]
@riccardone I feel like many would know that, but added it anyway :)

**Comment by gregoryyoung** [comment]
"
 > [!TIP]
> If a cluster has an even number of nodes, you risk 2 seperate clusters forming in the case of a network partition between the nodes. When the nodes rejoin the cluster, an election nominates the node with the most up to date data as `Master` and the previous `Master` shut down, generating an "offline truncation" log message. A non promotable clone helps prevent this situation in clusters with an even `ClusterSize`.

There seems to be some misunderstandings here...

1) There is no risk of two clusters with an even cluster size unless its misconfigured
2) "When the nodes rejoin the cluster, an election nominates the node with the most up to date data as `Master` and the previous `Master` shut down, generating an "offline truncation" log message."

The offline truncation message has to do with a very specific situation known as a deposed master. A master can be writing *ahead* of the other nodes in the cluster (masters optimistically write). As such a master can have things in its log that other nodes do not. When a master is deposed it may have written ahead in its log compared to other nodes. It is unknown whether a new master has the same data in the area that was written ahead. As such the deposed master needs to truncate any data that may have been written ahead but not acked by other nodes. 

Does this make sense?

**Comment by riccardone** [comment]
The scenario here is with a cluster size of 3 for example with 2 clones on a separate network. If a network partition happens is it possible to have that truncation error?

**Comment by gregoryyoung** [comment]
The error is *always* possible. You can make it happen deliberately on a local network ... just unplug the network cable of the master while writing. Truncation is due to the master optimistically writing to the log (and how replication works!)

**Comment by riccardone** [comment]
Ok understood. The tip here is... If your async replicas are NPC (and not clones) that error will not happen as they can't form or be part of a quorum. Is that correct?

**Comment by gregoryyoung** [comment]
" The tip here is... If your async replicas are NPC (and not clones) that error will not happen as they can't form or be part of a quorum. Is that correct?"

I am confused... The error can only happen on a deposed master.

**Comment by ChrisChinchilla** [comment]
OK, merging this now, there's a lot of other conversation around this we had in Slack, but I think this PR is ready.

**Pull request merged**
